language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g firebase-tools gulp bower
  - bower install
scrupt: gulp vulcanize
after_success:
  - firebase deploy --email $(FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}

