language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g firebase-tools gulp bower
  - bower install
script: gulp vulcanize
after_success:
  - firebase deploy --token "${FIREBASE_TOKEN}"

